insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (1, 1, 'China', 'Buhe', 'Meejo', '2018-08-29', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (2, 2, 'Philippines', 'Montecillo', 'Twitterbeat', '2019-04-15', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (3, 3, 'China', 'Gangdong', 'Trudeo', '2019-03-28', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (4, 4, 'Greece', 'Néa Filadélfeia', 'Viva', '2018-08-25', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (5, 5, 'Cuba', 'Manzanillo', 'Leexo', '2018-10-16', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (6, 6, 'Colombia', 'Ciénaga de Oro', 'Minyx', '2019-07-07', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (7, 7, 'Poland', 'Sarnaki', 'Tagtune', '2019-10-04', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (8, 8, 'South Korea', 'Gwangju', 'Yodel', '2019-06-21', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (9, 9, 'Nigeria', 'Okpoga', 'Kwideo', '2019-04-26', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (10, 10, 'Tunisia', 'Zarzis', 'Skimia', '2019-01-12', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (11, 11, 'Japan', 'Hita', 'Rhyloo', '2019-07-24', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (12, 12, 'Philippines', 'Damatulan', 'Gabtune', '2018-09-30', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (13, 13, 'Philippines', 'Lusacan', 'InnoZ', '2019-07-04', 'Warning', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (14, 14, 'China', 'Chigang', 'Kazio', '2018-10-31', 'Info', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (15, 15, 'China', 'Lecong', 'Aimbo', '2019-05-05', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (16, 16, 'Mongolia', 'Bayantal', 'Twinder', '2019-03-20', 'Info', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (17, 17, 'Argentina', 'Aristóbulo del Valle', 'Tanoodle', '2018-08-21', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (18, 18, 'China', 'Huangni', 'Twinte', '2018-12-01', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (19, 19, 'Philippines', 'Baugo', 'Oyondu', '2018-11-24', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (20, 20, 'China', 'Tiantang', 'Flashdog', '2019-07-18', 'Pending', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (21, 21, 'Afghanistan', 'Āsmār', 'Linklinks', '2018-11-27', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (22, 22, 'Syria', 'As Sūsah', 'Edgeblab', '2019-08-02', 'Warning', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (23, 23, 'China', 'Mingguang', 'Realmix', '2019-04-07', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (24, 24, 'Ireland', 'Piltown', 'Voomm', '2019-05-06', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (25, 25, 'Philippines', 'Polo', 'Topiclounge', '2019-04-15', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (26, 26, 'China', 'Dong’ao', 'Photojam', '2019-07-24', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (27, 27, 'Tanzania', 'Kisanga', 'Twimm', '2018-12-28', 'Warning', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (28, 28, 'Indonesia', 'Puutuga', 'Thoughtmix', '2019-03-30', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (29, 29, 'Honduras', 'Paujiles', 'Aibox', '2019-09-05', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (30, 30, 'Indonesia', 'Cikalong', 'Eire', '2019-10-15', 'Info', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (31, 31, 'Finland', 'Elimäki', 'Flipbug', '2019-04-19', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (32, 32, 'Indonesia', 'Sukolilo', 'Fivechat', '2019-09-23', 'Info', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (33, 33, 'Indonesia', 'Kebunkelapa', 'Quaxo', '2019-08-05', 'Warning', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (34, 34, 'China', 'Honglin', 'Dabtype', '2019-03-04', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (35, 35, 'Indonesia', 'Trambalan', 'Tagpad', '2019-06-13', 'Pending', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (36, 36, 'Zambia', 'Nakambala', 'Kamba', '2019-04-06', 'Pending', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (37, 37, 'Indonesia', 'Sukasari', 'Skajo', '2019-10-23', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (38, 38, 'Indonesia', 'Kalumpang', 'Jaxspan', '2019-10-18', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (39, 39, 'China', 'Daliuhao', 'Ntags', '2019-06-18', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (40, 40, 'Nicaragua', 'Dolores', 'Mydeo', '2019-06-16', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (41, 41, 'Czech Republic', 'Nové Strašecí', 'Avaveo', '2019-08-17', 'Success', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (42, 42, 'Indonesia', 'Temanjang', 'Mudo', '2018-08-19', 'Pending', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (43, 43, 'Russia', 'Ust’-Dzheguta', 'Wikizz', '2019-01-11', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (44, 44, 'Trinidad and Tobago', 'Paradise', 'Tanoodle', '2019-08-16', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (45, 45, 'United States', 'Las Vegas', 'Riffpedia', '2019-06-10', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (46, 46, 'Argentina', 'Alejo Ledesma', 'Yakijo', '2018-12-03', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (47, 47, 'France', 'Provins', 'Dynabox', '2019-04-09', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (48, 48, 'Uruguay', 'Santa Rosa', 'Realcube', '2019-08-20', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (49, 49, 'Russia', 'Karaidel’', 'Aivee', '2018-09-28', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (50, 50, 'China', 'Dayong', 'Yabox', '2018-08-17', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (51, 51, 'Pakistan', 'Būrewāla', 'Feedspan', '2018-08-18', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (52, 52, 'China', 'Peixing', 'Twitterwire', '2018-08-11', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (53, 53, 'Iran', 'Bandar-e Lengeh', 'Ntag', '2019-03-26', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (54, 54, 'Bhutan', 'Trashigang', 'Bubblemix', '2019-07-19', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (55, 55, 'Germany', 'Hamburg Sankt Pauli', 'Brainlounge', '2019-08-12', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (56, 56, 'China', 'Shanhou', 'Vitz', '2018-12-04', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (57, 57, 'Russia', 'Kurba', 'Skinte', '2019-01-31', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (58, 58, 'Czech Republic', 'Mostek', 'Agivu', '2019-05-06', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (59, 59, 'Czech Republic', 'Dolní Dvořiště', 'Dabjam', '2019-10-20', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (60, 60, 'Indonesia', 'Darungan', 'Wordware', '2019-06-15', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (61, 61, 'China', 'Yanwukou', 'Tagpad', '2019-05-05', 'Pending', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (62, 62, 'China', 'Jiutai', 'Flipbug', '2018-11-13', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (63, 63, 'Peru', 'Olmos', 'Zoombox', '2019-09-18', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (64, 64, 'Northern Mariana Islands', 'Saipan', 'Jaxworks', '2019-03-04', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (65, 65, 'Japan', 'Hiratachō', 'Youbridge', '2019-06-26', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (66, 66, 'Indonesia', 'Karangcombong', 'Livetube', '2018-11-13', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (67, 67, 'Japan', 'Gojō', 'InnoZ', '2018-10-24', 'Info', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (68, 68, 'Portugal', 'Lameira', 'Chatterbridge', '2018-10-01', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (69, 69, 'Croatia', 'Soljani', 'Thoughtblab', '2018-12-03', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (70, 70, 'China', 'Yanji', 'Jabberbean', '2019-06-09', 'Pending', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (71, 71, 'Denmark', 'Frederiksberg', 'Eadel', '2019-06-01', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (72, 72, 'Saudi Arabia', 'Unaizah', 'Tazz', '2019-06-25', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (73, 73, 'China', 'Tanshan', 'Realbridge', '2019-10-01', 'Warning', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (74, 74, 'Japan', 'Ōzu', 'Tekfly', '2019-01-15', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (75, 75, 'New Zealand', 'Riverton', 'Jabbertype', '2018-08-09', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (76, 76, 'Ireland', 'Belmullet', 'Photobug', '2018-11-01', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (77, 77, 'Poland', 'Jawor', 'Divape', '2018-09-25', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (78, 78, 'Russia', 'Lysogorskaya', 'Zoonoodle', '2019-08-29', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (79, 79, 'Argentina', 'La Francia', 'Voonte', '2019-10-20', 'Warning', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (80, 80, 'United States', 'Orlando', 'Skidoo', '2019-07-15', 'Pending', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (81, 81, 'China', 'Gongji', 'Vinder', '2019-04-16', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (82, 82, 'United States', 'Dallas', 'Devpoint', '2019-05-10', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (83, 83, 'Colombia', 'Colosó', 'Zoombeat', '2018-12-10', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (84, 84, 'Armenia', 'Dalarik', 'InnoZ', '2019-01-01', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (85, 85, 'Syria', 'Medaya', 'Riffwire', '2018-08-19', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (86, 86, 'Comoros', 'Chandra', 'Latz', '2018-11-28', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (87, 87, 'Ukraine', 'Krasnosilka', 'Tagfeed', '2018-12-29', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (88, 88, 'France', 'Amiens', 'Skynoodle', '2019-08-27', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (89, 89, 'Indonesia', 'Ngandangan', 'Gabtype', '2019-03-31', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (90, 90, 'Indonesia', 'Sumurwaru', 'Vinte', '2018-11-17', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (91, 91, 'France', 'Suresnes', 'Linkbridge', '2019-07-21', 'Info', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (92, 92, 'Thailand', 'Wichit', 'Gabcube', '2019-05-11', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (93, 93, 'China', 'Dongfeng', 'Fadeo', '2019-04-27', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (94, 94, 'Australia', 'Hobart', 'Jatri', '2019-07-26', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (95, 95, 'China', 'Pangushan', 'Leexo', '2018-12-04', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (96, 96, 'China', 'Chegang', 'Vinte', '2019-07-04', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (97, 97, 'Croatia', 'Gvozd', 'Quatz', '2019-05-11', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (98, 98, 'China', 'Tangga’an', 'Katz', '2019-07-19', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (99, 99, 'Indonesia', 'Pagelaran', 'Shufflebeat', '2019-08-15', 'Success', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (100, 100, 'Czech Republic', 'Jistebnice', 'Zoombox', '2019-05-27', 'Pending', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (101, 101, 'China', 'Yuyangguan', 'Cogilith', '2019-05-12', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (102, 102, 'China', 'Tangxi', 'Rhycero', '2019-04-08', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (103, 103, 'China', 'Dawang', 'Yata', '2019-03-08', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (104, 104, 'China', 'Duanjia', 'Ainyx', '2018-10-17', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (105, 105, 'Netherlands', 'Maastricht', 'Demivee', '2019-06-21', 'Pending', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (106, 106, 'Poland', 'Koronowo', 'Wordware', '2019-03-31', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (107, 107, 'Indonesia', 'Krajan Alasdowo', 'Twimm', '2018-09-19', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (108, 108, 'Republic of the Congo', 'Mossendjo', 'Skinte', '2018-10-15', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (109, 109, 'China', 'Liuduzhai', 'Flashspan', '2018-11-26', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (110, 110, 'Indonesia', 'Detik Satu', 'Divape', '2019-02-04', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (111, 111, 'South Africa', 'Kokstad', 'Mita', '2018-09-08', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (112, 112, 'Greece', 'Néa Kíos', 'Photojam', '2019-04-25', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (113, 113, 'Poland', 'Krotoszyn', 'Gigaclub', '2019-09-17', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (114, 114, 'Philippines', 'Lipa City', 'Gigashots', '2018-12-26', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (115, 115, 'Ukraine', 'Storozhnytsya', 'Vipe', '2019-09-04', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (116, 116, 'Russia', 'Manturovo', 'Jetpulse', '2019-05-19', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (117, 117, 'Colombia', 'Dagua', 'LiveZ', '2019-09-11', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (118, 118, 'Hungary', 'Pécs', 'Jaloo', '2018-11-16', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (119, 119, 'France', 'Villefranche-sur-Saône', 'Katz', '2019-09-26', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (120, 120, 'Ukraine', 'Velyka Lepetykha', 'Skimia', '2019-03-03', 'Warning', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (121, 121, 'China', 'Shouchang', 'Jayo', '2018-10-03', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (122, 122, 'Portugal', 'Várzea', 'Jetpulse', '2019-05-03', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (123, 123, 'Philippines', 'Santa Cruz', 'Oozz', '2018-10-21', 'Warning', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (124, 124, 'Russia', 'Gigant', 'Zoonoodle', '2018-08-15', 'Pending', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (125, 125, 'Indonesia', 'Tlogoagung', 'Realcube', '2018-12-05', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (126, 126, 'Bosnia and Herzegovina', 'Koran', 'Zoomlounge', '2019-04-06', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (127, 127, 'China', 'Shiwan', 'Tagpad', '2019-07-05', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (128, 128, 'Thailand', 'Lat Yao', 'Viva', '2018-12-14', 'Success', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (129, 129, 'Honduras', 'Nacaome', 'Jabbertype', '2019-06-13', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (130, 130, 'Azerbaijan', 'Sumqayıt', 'Quatz', '2018-12-28', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (131, 131, 'Mali', 'Diré', 'Gabvine', '2018-08-25', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (132, 132, 'Russia', 'Katav-Ivanovsk', 'Pixonyx', '2019-01-13', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (133, 133, 'Paraguay', 'Mbocayaty', 'Einti', '2019-01-10', 'Warning', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (134, 134, 'United States', 'Wichita', 'Jaxnation', '2019-01-10', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (135, 135, 'Burkina Faso', 'Titao', 'Devcast', '2018-12-21', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (136, 136, 'China', 'Xieqiao', 'Photofeed', '2019-03-05', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (137, 137, 'Philippines', 'Blinsung', 'Skyvu', '2019-06-16', 'Warning', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (138, 138, 'Indonesia', 'Beo', 'Tagtune', '2018-12-03', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (139, 139, 'Serbia', 'Krivaja', 'Innotype', '2018-11-05', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (140, 140, 'Indonesia', 'Oganlima', 'Skinte', '2019-01-05', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (141, 141, 'Canada', 'Saint-Rémi', 'Dabjam', '2018-08-06', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (142, 142, 'China', 'Binjiang', 'Flipstorm', '2019-05-14', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (143, 143, 'Philippines', 'Calinog', 'Edgeblab', '2019-09-08', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (144, 144, 'Equatorial Guinea', 'Ncue', 'Photolist', '2019-06-27', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (145, 145, 'China', 'Xiagang', 'Thoughtstorm', '2019-10-25', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (146, 146, 'China', 'Xiangyang', 'Dablist', '2019-10-24', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (147, 147, 'Czech Republic', 'Králův Dvůr', 'Zoonder', '2019-01-24', 'Warning', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (148, 148, 'Ukraine', 'Polonne', 'Kazio', '2018-08-16', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (149, 149, 'Georgia', 'Dioknisi', 'Mydeo', '2019-07-11', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (150, 150, 'China', 'Huangtu', 'Zoomzone', '2019-10-25', 'Warning', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (151, 151, 'Brazil', 'Maragogipe', 'Yodo', '2019-10-19', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (152, 152, 'Philippines', 'Wao', 'Meembee', '2018-08-03', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (153, 153, 'Indonesia', 'Krajan', 'Innojam', '2019-07-02', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (154, 154, 'Indonesia', 'Kowingir', 'Jabbersphere', '2019-05-03', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (155, 155, 'Ukraine', 'Dykan’ka', 'Camido', '2019-09-19', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (156, 156, 'China', 'Shuigou’ao', 'Einti', '2018-11-15', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (157, 157, 'Philippines', 'San Jose del Monte', 'Rhynoodle', '2018-10-06', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (158, 158, 'Philippines', 'San Agustin', 'Aimbu', '2018-12-18', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (159, 159, 'Bulgaria', 'Kula', 'BlogXS', '2018-11-04', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (160, 160, 'China', 'Xiongzhou', 'Voomm', '2019-09-17', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (161, 161, 'Canada', 'Lambton Shores', 'Dabfeed', '2018-08-10', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (162, 162, 'China', 'Zili', 'Thoughtworks', '2018-10-05', 'Info', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (163, 163, 'Sweden', 'Bromma', 'Zooxo', '2019-04-21', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (164, 164, 'France', 'Toulon', 'Rhybox', '2018-08-23', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (165, 165, 'China', 'Jiasi', 'Kwideo', '2019-01-08', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (166, 166, 'Yemen', 'Ḩadādah', 'Skalith', '2018-12-10', 'Info', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (167, 167, 'Dominican Republic', 'Río Grande', 'Realbuzz', '2019-04-18', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (168, 168, 'China', 'Xunzhong', 'Youbridge', '2019-07-29', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (169, 169, 'China', 'Yuchi', 'Kwinu', '2019-06-07', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (170, 170, 'Bangladesh', 'Netrakona', 'Minyx', '2019-08-12', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (171, 171, 'Madagascar', 'Amparafaravola', 'Ozu', '2019-07-24', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (172, 172, 'Poland', 'Osiek', 'Buzzster', '2019-07-15', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (173, 173, 'Philippines', 'Malinaw', 'Oyope', '2018-08-24', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (174, 174, 'China', 'Shuiquan', 'Skilith', '2019-09-16', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (175, 175, 'China', 'Baisha', 'Quaxo', '2018-10-12', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (176, 176, 'Argentina', 'El Carmen', 'Einti', '2019-06-22', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (177, 177, 'France', 'Lille', 'Meeveo', '2018-09-22', 'Pending', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (178, 178, 'Azerbaijan', 'Amirdzhan', 'Ozu', '2018-11-23', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (179, 179, 'Georgia', 'Dmanisi', 'Oloo', '2018-11-12', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (180, 180, 'Russia', 'Makhalino', 'Rhyzio', '2019-05-04', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (181, 181, 'Philippines', 'Santo Rosario', 'Fliptune', '2019-10-07', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (182, 182, 'South Africa', 'Camperdown', 'Abatz', '2019-02-23', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (183, 183, 'Russia', 'Karabanovo', 'Feednation', '2018-09-20', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (184, 184, 'South Africa', 'Benoni', 'Vinte', '2018-08-03', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (185, 185, 'Guinea', 'Siguiri', 'Zooveo', '2019-09-17', 'Pending', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (186, 186, 'Indonesia', 'Cipanggung', 'Dynabox', '2019-01-05', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (187, 187, 'Ukraine', 'Bolekhiv', 'Kayveo', '2019-04-10', 'Success', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (188, 188, 'China', 'Dushi', 'Trunyx', '2019-10-13', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (189, 189, 'Philippines', 'Dulag', 'Youfeed', '2018-12-09', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (190, 190, 'Armenia', 'Tsaghkaber', 'Realbuzz', '2018-12-03', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (191, 191, 'Germany', 'Berlin', 'Kwideo', '2019-07-25', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (192, 192, 'Colombia', 'Necoclí', 'Tazz', '2019-07-03', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (193, 193, 'Greece', 'Oropós', 'Eayo', '2018-11-08', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (194, 194, 'Chile', 'La Ligua', 'Gabtype', '2019-05-10', 'Success', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (195, 195, 'China', 'Suohe', 'Tanoodle', '2018-10-06', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (196, 196, 'Indonesia', 'Kedatuan', 'Fivebridge', '2018-08-02', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (197, 197, 'Samoa', 'Mulifanua', 'Jaxworks', '2019-05-09', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (198, 198, 'United States', 'Champaign', 'Vipe', '2019-07-14', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (199, 199, 'Argentina', 'Aviá Terai', 'Trupe', '2019-07-29', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (200, 200, 'Russia', 'Glyadyanskoye', 'Blogtag', '2018-08-05', 'Success', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (201, 201, 'China', 'Songfeng', 'Jabberbean', '2019-03-08', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (202, 202, 'Philippines', 'Cabuyao', 'Twitterbeat', '2019-08-03', 'Info', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (203, 203, 'Indonesia', 'Darunban', 'Skippad', '2019-10-02', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (204, 204, 'Japan', 'Okaya', 'Yodel', '2018-11-21', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (205, 205, 'China', 'Laba Goumen', 'Livefish', '2018-11-30', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (206, 206, 'Czech Republic', 'Netvořice', 'Skyvu', '2019-10-18', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (207, 207, 'China', 'Shuidun', 'Avaveo', '2019-07-20', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (208, 208, 'Russia', 'Lakha Nëvre', 'Zoonoodle', '2019-08-09', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (209, 209, 'Portugal', 'Aviúges', 'Photospace', '2018-11-08', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (210, 210, 'Yemen', 'As Sūq al Jadīd', 'Devcast', '2019-08-21', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (211, 211, 'Poland', 'Czerniewice', 'Yakijo', '2018-10-11', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (212, 212, 'Chad', 'Bol', 'Skinte', '2018-10-11', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (213, 213, 'Uruguay', 'Santa Rosa', 'Quatz', '2019-10-17', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (214, 214, 'China', 'Domartang', 'Viva', '2019-05-01', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (215, 215, 'Nigeria', 'Zuru', 'Mita', '2018-12-09', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (216, 216, 'China', 'Rinbung', 'Pixope', '2018-12-09', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (217, 217, 'Peru', 'Nueva Arica', 'Skaboo', '2019-06-25', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (218, 218, 'Sri Lanka', 'Ampara', 'Livefish', '2018-12-13', 'Info', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (219, 219, 'France', 'Belfort', 'Ainyx', '2019-02-08', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (220, 220, 'China', 'Weishan', 'Eabox', '2019-01-27', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (221, 221, 'Portugal', 'Donim', 'Zoomzone', '2019-06-28', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (222, 222, 'United States', 'Jefferson City', 'Rhybox', '2019-02-05', 'Success', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (223, 223, 'Thailand', 'Sanom', 'Realcube', '2019-04-13', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (224, 224, 'Philippines', 'Eguia', 'Photojam', '2019-01-05', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (225, 225, 'Argentina', 'Rufino', 'Twitterbeat', '2019-07-25', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (226, 226, 'Philippines', 'Camias', 'Realmix', '2019-09-24', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (227, 227, 'China', 'Houxiang', 'Plambee', '2019-09-17', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (228, 228, 'China', 'Shangtang', 'Livetube', '2018-08-05', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (229, 229, 'New Zealand', 'Waitangi', 'Wordify', '2019-01-16', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (230, 230, 'Poland', 'Przytyk', 'Buzzbean', '2019-06-07', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (231, 231, 'Poland', 'Borzęta', 'Browsebug', '2019-07-02', 'Pending', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (232, 232, 'France', 'Strasbourg', 'Youbridge', '2018-10-08', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (233, 233, 'Bhutan', 'Panbang', 'Trudeo', '2018-09-13', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (234, 234, 'Brazil', 'São Sepé', 'Jetwire', '2019-04-06', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (235, 235, 'Czech Republic', 'Zbraslav', 'Kaymbo', '2018-09-15', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (236, 236, 'Peru', 'Haquira', 'Oodoo', '2019-04-11', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (237, 237, 'Canada', 'Ladner', 'Flashpoint', '2019-09-22', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (238, 238, 'Indonesia', 'Panineungan', 'Eabox', '2019-03-07', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (239, 239, 'China', 'Lezhu', 'Skaboo', '2019-03-13', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (240, 240, 'China', 'Zhongbu', 'Babbleopia', '2018-10-17', 'Warning', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (241, 241, 'Japan', 'Muramatsu', 'Dabfeed', '2018-09-17', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (242, 242, 'Philippines', 'Placer', 'Twinte', '2019-06-22', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (243, 243, 'Russia', 'Polyarnyy', 'Wikivu', '2019-03-17', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (244, 244, 'Belarus', 'Klimavichy', 'Zoomzone', '2019-04-21', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (245, 245, 'Portugal', 'Meruge', 'Feedfish', '2019-03-20', 'Success', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (246, 246, 'Brazil', 'São Joaquim da Barra', 'Linklinks', '2018-08-26', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (247, 247, 'Greece', 'Lefkímmi', 'Blogspan', '2019-09-26', 'Pending', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (248, 248, 'Colombia', 'Puerto Boyacá', 'Skynoodle', '2018-11-05', 'Info', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (249, 249, 'Laos', 'Lamam', 'Skajo', '2019-07-28', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (250, 250, 'Argentina', 'Comandante Luis Piedra Buena', 'Innotype', '2019-10-20', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (251, 251, 'France', 'Morangis', 'Dabjam', '2019-02-23', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (252, 252, 'Hungary', 'Sopron', 'Chatterpoint', '2019-02-17', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (253, 253, 'Russia', 'Pavino', 'Edgewire', '2019-05-23', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (254, 254, 'Czech Republic', 'Frýdek-Místek', 'Reallinks', '2019-03-24', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (255, 255, 'Malawi', 'Chipoka', 'Ozu', '2019-09-15', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (256, 256, 'Benin', 'Kétou', 'Blogspan', '2018-10-09', 'Warning', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (257, 257, 'Philippines', 'Tarangnan', 'Jabbersphere', '2019-07-03', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (258, 258, 'Czech Republic', 'Slavkov u Brna', 'Oyonder', '2019-02-09', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (259, 259, 'Brazil', 'Nazaré da Mata', 'Jayo', '2018-09-15', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (260, 260, 'Indonesia', 'Gununganyartambak Tengah', 'Quatz', '2019-05-08', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (261, 261, 'China', 'Gaotaizi', 'Kanoodle', '2018-09-21', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (262, 262, 'Indonesia', 'Kawangkoan', 'Voomm', '2019-08-04', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (263, 263, 'Indonesia', 'Jatirejo', 'Divape', '2019-01-09', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (264, 264, 'Poland', 'Kołczygłowy', 'Mynte', '2018-12-22', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (265, 265, 'United States', 'Anchorage', 'Roodel', '2018-11-02', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (266, 266, 'Russia', 'Pervoural’sk', 'Quimba', '2019-08-27', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (267, 267, 'Greece', 'Stírion', 'Oyoba', '2018-11-01', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (268, 268, 'Brazil', 'Canoinhas', 'Lazzy', '2019-10-21', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (269, 269, 'China', 'Zhuangta', 'Mycat', '2018-10-16', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (270, 270, 'Russia', 'Maykor', 'Linklinks', '2018-12-01', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (271, 271, 'United States', 'Rockford', 'Feedmix', '2018-08-28', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (272, 272, 'China', 'Chiduo', 'Meedoo', '2019-10-01', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (273, 273, 'France', 'Cosne-Cours-sur-Loire', 'Tekfly', '2018-08-28', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (274, 274, 'Philippines', 'Taytayan', 'Tazzy', '2019-07-27', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (275, 275, 'Brazil', 'Lauro de Freitas', 'Eimbee', '2019-03-03', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (276, 276, 'China', 'Hechuan', 'Teklist', '2019-09-15', 'Warning', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (277, 277, 'Philippines', 'Burirao', 'Voonte', '2019-03-30', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (278, 278, 'Sweden', 'Uppsala', 'Twinder', '2019-06-14', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (279, 279, 'Canada', 'Prévost', 'Vinder', '2019-06-20', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (280, 280, 'China', 'Lieyu', 'Devpulse', '2018-10-02', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (281, 281, 'United States', 'Vienna', 'Buzzster', '2019-05-05', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (282, 282, 'Japan', 'Kamojimachō-jōgejima', 'Youspan', '2019-05-23', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (283, 283, 'Russia', 'Volokonovka', 'Oyoloo', '2018-12-06', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (284, 284, 'Uzbekistan', 'Chinoz', 'Avamba', '2019-05-23', 'Info', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (285, 285, 'Denmark', 'København', 'Lazzy', '2019-09-29', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (286, 286, 'China', 'Hongxing', 'Digitube', '2018-09-10', 'Info', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (287, 287, 'France', 'Quimper', 'DabZ', '2018-11-06', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (288, 288, 'Philippines', 'Moog', 'Ainyx', '2019-01-26', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (289, 289, 'China', 'Shaoyang', 'Centimia', '2019-06-20', 'Warning', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (290, 290, 'Philippines', 'Bulacnin', 'Edgeblab', '2019-10-22', 'Info', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (291, 291, 'Croatia', 'Ferdinandovac', 'Aivee', '2018-11-30', 'Warning', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (292, 292, 'China', 'Songhe', 'Skimia', '2019-03-04', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (293, 293, 'Russia', 'Kingisepp', 'Cogibox', '2019-03-03', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (294, 294, 'Philippines', 'Tiling', 'Latz', '2019-05-20', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (295, 295, 'Indonesia', 'Lewopao', 'Shufflester', '2019-09-04', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (296, 296, 'Sweden', 'Hagfors', 'Aimbu', '2019-02-09', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (297, 297, 'China', 'Longgang', 'Blognation', '2019-02-01', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (298, 298, 'Ukraine', 'Pniv', 'Buzzshare', '2019-07-13', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (299, 299, 'North Korea', 'Kowŏn-ŭp', 'Devpoint', '2019-07-12', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (300, 300, 'Bulgaria', 'Opaka', 'Photospace', '2019-09-05', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (301, 301, 'Colombia', 'Gigante', 'Mynte', '2019-09-17', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (302, 302, 'Poland', 'Rydułtowy', 'Tagpad', '2019-02-11', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (303, 303, 'Indonesia', 'Pandaan', 'Zoonder', '2019-06-19', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (304, 304, 'Philippines', 'Lingion', 'Realcube', '2018-08-14', 'Warning', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (305, 305, 'Indonesia', 'Montongtebolak', 'Kazu', '2018-12-24', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (306, 306, 'Indonesia', 'Luthu', 'Riffwire', '2019-04-02', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (307, 307, 'Russia', 'Lakinsk', 'Linkbridge', '2018-12-07', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (308, 308, 'Jamaica', 'Wakefield', 'Trunyx', '2019-09-30', 'Warning', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (309, 309, 'France', 'Boulogne-Billancourt', 'Janyx', '2019-01-31', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (310, 310, 'Indonesia', 'Kablukan', 'Brightdog', '2019-01-14', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (311, 311, 'Mongolia', 'Enhtal', 'Abata', '2019-09-06', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (312, 312, 'China', 'Sanxi', 'Browseblab', '2019-08-25', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (313, 313, 'United States', 'Akron', 'Abatz', '2019-02-14', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (314, 314, 'Russia', 'Choya', 'Zoomcast', '2019-10-11', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (315, 315, 'Indonesia', 'Gerelayang', 'Pixonyx', '2019-09-16', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (316, 316, 'Indonesia', 'Sidomakmur', 'Latz', '2019-01-17', 'Warning', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (317, 317, 'Sudan', 'Um Jar Al Gharbiyya', 'Twimm', '2018-12-19', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (318, 318, 'Indonesia', 'Lundo', 'Divape', '2018-10-15', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (319, 319, 'Philippines', 'Santa Cruz', 'Vitz', '2018-10-27', 'Warning', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (320, 320, 'Russia', 'Sovetskaya', 'Abata', '2019-05-21', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (321, 321, 'Japan', 'Haebaru', 'Zoombox', '2019-09-12', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (322, 322, 'Greece', 'Kalpáki', 'Realbuzz', '2019-10-21', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (323, 323, 'Indonesia', 'Krajan Curahcotok', 'Demizz', '2019-07-19', 'Warning', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (324, 324, 'Cyprus', 'Léfka', 'Thoughtstorm', '2019-03-23', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (325, 325, 'China', 'Dongjiao', 'Oyoyo', '2018-10-02', 'Success', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (326, 326, 'Luxembourg', 'Stadtbredimus', 'Camido', '2019-05-30', 'Warning', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (327, 327, 'Poland', 'Sietesz', 'Topicware', '2018-12-28', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (328, 328, 'Burundi', 'Buganda', 'Realblab', '2018-09-29', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (329, 329, 'China', 'Tehetu', 'Yakidoo', '2019-10-20', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (330, 330, 'Colombia', 'Líbano', 'Lazzy', '2018-12-14', 'Warning', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (331, 331, 'Japan', 'Yasugichō', 'Twitternation', '2019-08-18', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (332, 332, 'Indonesia', 'Bukabu', 'Quire', '2019-08-21', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (333, 333, 'Sweden', 'Umeå', 'Jabberstorm', '2019-04-11', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (334, 334, 'Philippines', 'Gubat', 'Voonte', '2019-02-25', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (335, 335, 'Russia', 'Verkhneye Kazanishche', 'Divavu', '2019-03-19', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (336, 336, 'China', 'Nanjiao', 'Jetpulse', '2019-06-22', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (337, 337, 'China', 'Xiangqiao', 'Tekfly', '2019-01-30', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (338, 338, 'China', 'Tonghu', 'Pixonyx', '2018-10-16', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (339, 339, 'China', 'Yangjia', 'Blogspan', '2019-01-05', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (340, 340, 'Sweden', 'Boden', 'Photobug', '2019-09-15', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (341, 341, 'Indonesia', 'Timahankrajan', 'Kazu', '2019-01-29', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (342, 342, 'Poland', 'Czyżowice', 'Voolia', '2018-08-19', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (343, 343, 'New Zealand', 'Waitara', 'Kwideo', '2018-08-16', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (344, 344, 'Zambia', 'Kalabo', 'Dabjam', '2018-08-06', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (345, 345, 'Philippines', 'Clarin', 'Youbridge', '2019-02-06', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (346, 346, 'China', 'Longzhouwan', 'JumpXS', '2018-10-16', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (347, 347, 'United States', 'Portland', 'Wikizz', '2019-03-21', 'Success', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (348, 348, 'Philippines', 'Batobato', 'Lazz', '2018-09-13', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (349, 349, 'United States', 'Cumming', 'Kamba', '2019-06-09', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (350, 350, 'Dominican Republic', 'Otra Banda', 'Trudoo', '2019-01-21', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (351, 351, 'China', 'Limushan', 'Agivu', '2018-09-07', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (352, 352, 'China', 'Songgui', 'Aimbo', '2018-08-19', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (353, 353, 'Poland', 'Wołczyn', 'Trunyx', '2019-02-04', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (354, 354, 'Mexico', 'Lazaro Cardenas', 'Dablist', '2019-02-05', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (355, 355, 'Philippines', 'Babak', 'Bubblebox', '2019-05-13', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (356, 356, 'China', 'Taoyang', 'Babblestorm', '2019-03-20', 'Success', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (357, 357, 'Poland', 'Ryjewo', 'Dynabox', '2018-08-26', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (358, 358, 'China', 'Matou', 'Fanoodle', '2019-02-25', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (359, 359, 'Belarus', 'Urechcha', 'Zava', '2018-08-03', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (360, 360, 'Finland', 'Hausjärvi', 'Divavu', '2019-10-15', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (361, 361, 'Indonesia', 'Natu', 'Digitube', '2019-10-05', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (362, 362, 'Greece', 'Mouzáki', 'Kwideo', '2019-09-28', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (363, 363, 'Yemen', 'Al Qaţn', 'Kwinu', '2019-10-30', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (364, 364, 'Philippines', 'Cabitan', 'Meetz', '2019-03-29', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (365, 365, 'Indonesia', 'Karangnunggal', 'Cogilith', '2019-08-27', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (366, 366, 'Poland', 'Godziszów Pierwszy', 'Skyvu', '2019-01-13', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (367, 367, 'Dominican Republic', 'Pedro Sánchez', 'Brainbox', '2019-06-05', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (368, 368, 'Philippines', 'Jolo', 'Lajo', '2018-12-16', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (369, 369, 'France', 'Lunéville', 'Avaveo', '2019-07-07', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (370, 370, 'Indonesia', 'Kebonagung', 'Photofeed', '2019-08-09', 'Info', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (371, 371, 'France', 'Montpellier', 'Zoomzone', '2019-01-17', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (372, 372, 'Sweden', 'Mariefred', 'Browsedrive', '2019-08-25', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (373, 373, 'Kyrgyzstan', 'Kant', 'Devcast', '2019-10-10', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (374, 374, 'China', 'Yisuhe', 'Brightdog', '2019-10-19', 'Warning', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (375, 375, 'Czech Republic', 'Jindřichov', 'Topicware', '2019-09-19', 'Success', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (376, 376, 'Indonesia', 'Coratatal', 'LiveZ', '2019-09-07', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (377, 377, 'Thailand', 'Wang Yang', 'Layo', '2019-01-12', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (378, 378, 'Panama', 'Boca de Parita', 'Oyoba', '2019-07-15', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (379, 379, 'France', 'Lyon', 'Skyba', '2019-06-20', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (380, 380, 'Brazil', 'Guapimirim', 'Yodo', '2018-08-16', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (381, 381, 'Brazil', 'Lagarto', 'Shufflebeat', '2019-06-06', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (382, 382, 'Sweden', 'Örebro', 'Ooba', '2019-09-25', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (383, 383, 'Peru', 'Potoni', 'Topdrive', '2019-04-11', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (384, 384, 'Mexico', 'Ojo de Agua', 'Twitterbeat', '2018-12-03', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (385, 385, 'Tanzania', 'Katumba', 'Jatri', '2018-08-06', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (386, 386, 'Japan', 'Menuma', 'Skajo', '2019-04-10', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (387, 387, 'Canada', 'Olds', 'Youfeed', '2019-10-08', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (388, 388, 'Indonesia', 'Long Loreh', 'Feedspan', '2019-09-14', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (389, 389, 'China', 'Heishan', 'Youspan', '2019-10-22', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (390, 390, 'Brazil', 'Cruz Alta', 'Ntag', '2019-10-15', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (391, 391, 'Poland', 'Włoszczowa', 'Dabvine', '2018-08-22', 'Pending', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (392, 392, 'Albania', 'Librazhd-Qendër', 'Realblab', '2018-09-24', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (393, 393, 'Zimbabwe', 'Gweru', 'Zava', '2019-10-04', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (394, 394, 'Zambia', 'Chipata', 'Thoughtstorm', '2018-11-06', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (395, 395, 'Bosnia and Herzegovina', 'Barice', 'Edgeblab', '2019-06-23', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (396, 396, 'Mexico', 'Buenavista', 'Feednation', '2018-08-06', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (397, 397, 'Russia', 'Staromyshastovskaya', 'Devshare', '2018-11-06', 'Warning', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (398, 398, 'Greece', 'Anaráchi', 'Rhycero', '2019-09-09', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (399, 399, 'Swaziland', 'Mhlume', 'Buzzster', '2019-02-21', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (400, 400, 'France', 'Paris 12', 'Shufflester', '2019-03-24', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (401, 401, 'China', 'Yuncao', 'Quamba', '2019-10-05', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (402, 402, 'Venezuela', 'Porlamar', 'Jaxworks', '2019-05-11', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (403, 403, 'Mongolia', 'Baruunsuu', 'Meejo', '2018-09-07', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (404, 404, 'China', 'Daqin Tal', 'Twiyo', '2019-08-10', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (405, 405, 'Yemen', 'Ḩurayḑah', 'Eayo', '2019-02-02', 'Warning', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (406, 406, 'South Korea', 'Gwangjeok', 'Trupe', '2019-03-20', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (407, 407, 'Indonesia', 'Koroyo', 'Dabtype', '2018-10-30', 'Info', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (408, 408, 'El Salvador', 'Santa Ana', 'Kazio', '2018-12-04', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (409, 409, 'Portugal', 'Penelas', 'Zooxo', '2019-10-30', 'Success', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (410, 410, 'Japan', 'Otofuke', 'Yabox', '2019-03-18', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (411, 411, 'Brazil', 'Japeri', 'Riffwire', '2019-05-23', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (412, 412, 'Ukraine', 'Storozhynets’', 'Babbleopia', '2019-05-30', 'Warning', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (413, 413, 'Yemen', 'Az Zāhir', 'Fliptune', '2019-10-12', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (414, 414, 'Morocco', 'Taounate', 'Skiba', '2018-12-05', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (415, 415, 'France', 'Longwy', 'Skivee', '2019-01-22', 'Pending', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (416, 416, 'Georgia', 'Bagdadi', 'Brainbox', '2018-12-11', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (417, 417, 'China', 'Suizhong', 'Fanoodle', '2019-01-27', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (418, 418, 'China', 'Yingjiang', 'Mynte', '2019-03-12', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (419, 419, 'Vietnam', 'Thị Trấn Yên Thế', 'Jaloo', '2018-10-22', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (420, 420, 'Russia', 'Radovitskiy', 'Fadeo', '2019-02-13', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (421, 421, 'Namibia', 'Otavi', 'Yodo', '2019-09-24', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (422, 422, 'Nicaragua', 'Nandaime', 'Livepath', '2018-11-28', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (423, 423, 'Japan', 'Nanto-shi', 'Twitternation', '2018-10-27', 'Success', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (424, 424, 'Philippines', 'Luna', 'Vinder', '2019-03-09', 'Canceled', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (425, 425, 'China', 'Xinjiezhen', 'Oyope', '2018-12-31', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (426, 426, 'China', 'Xishiqiao', 'Yacero', '2019-01-28', 'Info', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (427, 427, 'Afghanistan', 'Markaz-e Ḩukūmat-e Darwēshān', 'Yadel', '2019-05-13', 'Warning', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (428, 428, 'Pakistan', 'Risālpur', 'Edgeclub', '2019-03-05', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (429, 429, 'Mexico', 'El Mirador', 'Mita', '2019-04-21', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (430, 430, 'Philippines', 'Wawa', 'Demimbu', '2019-02-15', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (431, 431, 'Japan', 'Miharu', 'Edgepulse', '2018-09-07', 'Pending', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (432, 432, 'Ukraine', 'Chornukhyne', 'Photofeed', '2019-09-04', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (433, 433, 'Liberia', 'Harper', 'Demivee', '2018-09-17', 'Warning', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (434, 434, 'Ireland', 'Rathangan', 'Browsebug', '2018-08-09', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (435, 435, 'China', 'Yangzhong', 'Gabcube', '2018-11-25', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (436, 436, 'Russia', 'Valday', 'Divape', '2018-12-10', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (437, 437, 'China', 'Tongtuan', 'Dabshots', '2019-04-25', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (438, 438, 'China', 'Shangjing', 'Meetz', '2019-02-06', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (439, 439, 'Thailand', 'Sapphaya', 'Livetube', '2018-12-31', 'Success', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (440, 440, 'Philippines', 'Nama', 'Eamia', '2019-06-11', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (441, 441, 'China', 'Huayuan', 'Yadel', '2019-09-25', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (442, 442, 'Philippines', 'Alaminos', 'Oodoo', '2019-09-07', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (443, 443, 'Thailand', 'Kut Rang', 'Reallinks', '2019-07-27', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (444, 444, 'China', 'Mawu', 'Ozu', '2019-08-26', 'Warning', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (445, 445, 'Indonesia', 'Balesari', 'Zoombeat', '2019-03-04', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (446, 446, 'Egypt', 'Kousa', 'Wikido', '2018-08-22', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (447, 447, 'Nigeria', 'Adani', 'Tagtune', '2019-08-30', 'Pending', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (448, 448, 'China', 'Changqi', 'Yabox', '2019-06-03', 'Warning', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (449, 449, 'Colombia', 'Cáceres', 'Kwilith', '2018-12-29', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (450, 450, 'Indonesia', 'Kampungsusah', 'Ozu', '2019-04-12', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (451, 451, 'Nigeria', 'Iwo', 'Katz', '2019-06-19', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (452, 452, 'Japan', 'Tsukuba', 'Thoughtstorm', '2019-07-15', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (453, 453, 'Sweden', 'Bromölla', 'Podcat', '2018-12-02', 'Warning', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (454, 454, 'Brazil', 'Ilhabela', 'Jabberstorm', '2018-12-26', 'Info', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (455, 455, 'China', 'Wangba', 'Youtags', '2019-07-29', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (456, 456, 'Portugal', 'Vale de Rolas', 'Myworks', '2018-09-15', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (457, 457, 'Poland', 'Golub-Dobrzyń', 'Zoomzone', '2019-05-16', 'Delivered', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (458, 458, 'Russia', 'Rudnya', 'Meetz', '2019-04-22', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (459, 459, 'South Korea', 'Hwado', 'Thoughtbeat', '2019-01-18', 'Warning', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (460, 460, 'Czech Republic', 'Velké Karlovice', 'Wikibox', '2019-06-24', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (461, 461, 'Albania', 'Derjan', 'Voolith', '2019-10-27', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (462, 462, 'Indonesia', 'Busungbiu', 'Topiclounge', '2019-05-20', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (463, 463, 'Albania', 'Finiq', 'Skinte', '2019-02-17', 'Success', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (464, 464, 'Indonesia', 'Koa', 'Quimm', '2019-05-23', 'Info', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (465, 465, 'Venezuela', 'Tinaco', 'Snaptags', '2019-08-01', 'Pending', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (466, 466, 'China', 'Erfangping', 'Jaloo', '2019-09-27', 'Success', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (467, 467, 'Argentina', 'Brinkmann', 'Skalith', '2018-08-13', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (468, 468, 'Portugal', 'Quintela', 'Gabtune', '2019-01-06', 'Pending', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (469, 469, 'China', 'Maojia', 'Gabcube', '2018-12-24', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (470, 470, 'Argentina', 'Campana', 'Zooxo', '2018-08-14', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (471, 471, 'China', 'Huangtu', 'Riffwire', '2019-03-25', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (472, 472, 'Albania', 'Karbunara e Vogël', 'Mydo', '2019-06-19', 'Success', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (473, 473, 'France', 'Vanves', 'Brainbox', '2018-10-05', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (474, 474, 'Philippines', 'Barong', 'Divanoodle', '2019-03-19', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (475, 475, 'China', 'Pingqiao', 'Centizu', '2018-09-30', 'Warning', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (476, 476, 'New Zealand', 'Levin', 'Oodoo', '2018-12-27', 'Warning', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (477, 477, 'United States', 'Phoenix', 'Mynte', '2018-09-25', 'Danger', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (478, 478, 'China', 'Tanbu', 'Skyba', '2019-08-07', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (479, 479, 'Indonesia', 'Pasar', 'Feedfish', '2019-10-01', 'Pending', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (480, 480, 'Guatemala', 'Tamahú', 'Skynoodle', '2019-05-28', 'Warning', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (481, 481, 'Philippines', 'Tabu', 'Topicshots', '2019-08-16', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (482, 482, 'Brazil', 'Esteio', 'Voomm', '2018-09-28', 'Delivered', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (483, 483, 'Poland', 'Wałcz', 'Mynte', '2019-01-07', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (484, 484, 'China', 'Xietang', 'Babbleset', '2019-06-22', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (485, 485, 'Netherlands', 'Lelystad', 'Topicstorm', '2018-12-16', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (486, 486, 'Peru', 'Bretaña', 'Voonyx', '2019-01-27', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (487, 487, 'Mongolia', 'Dzuunmod', 'Bluezoom', '2019-10-13', 'Canceled', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (488, 488, 'Mexico', 'San Isidro', 'Twiyo', '2018-12-15', 'Warning', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (489, 489, 'Indonesia', 'Sambirobyong', 'Zoozzy', '2018-12-06', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (490, 490, 'Brazil', 'Caucaia', 'Tanoodle', '2018-08-18', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (491, 491, 'China', 'Yangliu', 'Muxo', '2019-05-07', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (492, 492, 'Poland', 'Janikowo', 'Quimba', '2019-07-23', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (493, 493, 'Argentina', 'Aguilares', 'Aibox', '2019-03-12', 'Danger', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (494, 494, 'Indonesia', 'Sambong', 'Livepath', '2019-04-19', 'Canceled', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (495, 495, 'China', 'Dahuaishu', 'Youspan', '2018-10-28', 'Success', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (496, 496, 'China', 'Dongxi', 'Ailane', '2018-11-02', 'Danger', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (497, 497, 'France', 'Caen', 'Skidoo', '2019-10-11', 'Info', 'Direct');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (498, 498, 'Indonesia', 'Kadugede', 'Dabtype', '2018-09-01', 'Delivered', 'Online');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (499, 499, 'Ukraine', 'Kharkiv', 'Topicware', '2018-08-01', 'Warning', 'Retail');
insert into orders (RecordID, OrderID, Country, ShipCity, CompanyAgent, ShipDate, Status, Type) values (500, 500, 'Panama', 'Gómez', 'Yodo', '2018-08-29', 'Danger', 'Online');


INSERT INTO product(id, name, summary, detail) VALUES (1, 'iPhone', 'Apple mobile device', 'The iPhone is a line of smartphones designed and marketed by Apple Inc. All generations of the iPhone use Apple''s iOS mobile operating system software. The first-generation iPhone was released on June 29, 2007, and multiple new hardware iterations with new iOS releases have been released since.');
INSERT INTO product(id, name, summary, detail) VALUES (2, 'XA1 Ultra', 'Smartphone, tablet, phablet', 'Xperia is the brand name of smartphones and tablets from Sony Mobile. The name Xperia is derived from the word "experience", and was first used in the Xperia X1 tagline, "I Xperia the best".');